### ISSUE TITLE
MSSQL 2000 can't connect

### ISSUE THREAD

**Issue by Nas-au** [xgenecloud/xgenecloud#21]
**Bug is in**
[X] Desktop App
[X] REST API Framework 

**Describe the bug**
i,m trying to connect to MSSQL 2000 but connection is refused.

**Comment by o1lab** [comment]
Could you check if [knex](http://knexjs.org/) works with MSSQL 2000 and let us know your finding please. 

Will try to find a docker image for 2000 in meanwhile - we are on *nix OS mostly.

**Comment by Miazzy** [comment]
➜  rest-api git:(master) cd ..              
➜  Workspace xc new newecology
? 🔥 Choose SQL Database type	: mssql
? 👉 Enter database host name	: 192.168.2.52
? 👉 Enter database port number	: 1433
? 👉 Enter database username	: sa
? 🙈 Enter database password	: ***
? 👉 Enter database/schema name	: newecology
? 🚀 Enter API type to generate	: REST APIs
tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. ../../../../usr/local/lib/node_modules/xc-cli/node_modules/mssql/lib/tedious/connection-pool.js:61:23
(node:50829) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.

😩 Test connection failed for : mssql://192.168.2.52:1433?u=sa&p=123&d=newecology

➜  Workspace

**Comment by Miazzy** [comment]
can not connect sql server too!

this is debug info :

➜ rest-api git:(master) cd ..
➜ Workspace xc new newecology
? 🔥 Choose SQL Database type : mssql
? 👉 Enter database host name : 192.168.2.52
? 👉 Enter database port number : 1433
? 👉 Enter database username : sa
? 🙈 Enter database password : ***
? 👉 Enter database/schema name : newecology
? 🚀 Enter API type to generate : REST APIs
tedious deprecated The default value for config.options.enableArithAbort will change from false to true in the next major version of tedious. Set the value to true or false explicitly to silence this message. ../../../../usr/local/lib/node_modules/xc-cli/node_modules/mssql/lib/tedious/connection-pool.js:61:23
(node:50829) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.

😩 Test connection failed for : mssql://192.168.2.52:1433?u=sa&p=123&d=newecology

➜ Workspace

**Comment by o1lab** [comment]
Which version of mssql is it ?

Try if a simple knex connection is working 

```
var knex = require('knex')({
  client: 'mssql',
  connection: {
    host : '192.168.2.52
    user : 'sa',
    password : '***',
    database : 'newecology
  }
});

(async () => {
    try {
        // replace __TABLE__NAME__
        var rows = knex.select('*').from('__TABLE__NAME__')
        console.log(JSON.stringify(rows));
    } catch (e) {
        console.log(e);
    }
})();
```

**Comment by LukasCCB** [comment]
I have this same problem.

 [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
