### ISSUE TITLE
Problem of creating REST API

### ISSUE THREAD

**Issue by InVinCiblezz** [xgenecloud/xgenecloud#29]
**Bug is in**
[X] CLI
[X] Desktop App
[X] REST API Framework 
[ ] GraphQL API Framework

put letter x within relevant [ ] above

**Describe the bug**
After installing xgenecloud, I want to create a project using xc new project_name
However, after I entering the information of MySQL, 😩 Test connection failed for : mysql://localhost:3306?u=root&p=&d=xxx
And the GUI also said ER_NOT_SUPPORTED_AUTH_MODE. My MySQL version is 8.0.19.

**To Reproduce**
Bulleted points to reproduce the behavior

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18670530/88018110-a6567d00-caec-11ea-80bc-a29db7c3c393.png)

**Desktop (please complete the following information):**
 - CLI Version [e.g. 0.3.1] 0.3.16
 - Desktop App Version [e.g. 0.3.1] 0.3.16
 - xc-data-mapper version [e.g. 0.3.1]
 - xc-core version [e.g. 0.3.1] 
 - OS: [e.g. Mac/Win/Linux] MAC

**Additional context**

**Comment by InVinCiblezz** [comment]
Thanks a lot @o1lab !
and I have another question that could we create personal APIs?
like using one SQL to create some APIs that are different from the auto-generated ones.
Thanks a lot!

**Comment by o1lab** [comment]
Yes!

When we create APIs - we are also creating API source code (express.js / node.js) in the project folder :)
You can easily add additional APIs - please hop on to our discord.  I can help you started over a zoom call.

**Comment by o1lab** [comment]
https://discord.gg/5RgZmkW
