### ISSUE TITLE
Error on npm run

### ISSUE THREAD

**Issue by Tanneguy** [xgenecloud/xgenecloud#30]
**Bug is in**
[ ] CLI
[ ] Desktop App
[x] REST API Framework 
[ ] GraphQL API Framework

**Describe the bug**

Error message at the *npm run* stage of the REST API generation.

ER_BAD_FIELD_ERROR : Unknow column 'expired' in where clause at Query.Sequence.__packetToError
node_modules/mysql/lib/protocol/sequences/Sequences.js:47.14

**To Reproduce**

> xc new sql-api
> connect to DB
> Save project
> click on Generate REST Code

 

**Expected behavior**

No error message

**Screenshots**

**Desktop (please complete the following information):**
 - CLI Version  0.3.2
 - Desktop App 
 - xc-data-mapper 
 - xc-core version 
 - OS: Mac High Sierra

**Additional context**
Straight install / REST API generation on existing DB.

**Comment by o1lab** [comment]
Could you please try with the latest desktop app version ([0.3.16](https://github.com/xgenecloud/xc-desktop-app/releases/tag/v0.3.16))

**Comment by o1lab** [comment]
+ please the paste the error log / stack if you are still facing the issue

**Comment by Tanneguy** [comment]
I tried with 3.0.16, same deal

I'd love to paste the stack trace, but somehow copy/paste doesn't work in the app, and I don't see a way to run the whole process through the CLI only. I will try a screenshot

**Comment by Tanneguy** [comment]
![image](https://user-images.githubusercontent.com/3609703/89714212-6c66f100-d99d-11ea-9754-9ccf9382456b.png)
![image](https://user-images.githubusercontent.com/3609703/89714257-a2a47080-d99d-11ea-8354-5be9f3fb837e.png)

**Comment by o1lab** [comment]
I guess it might be mysql connection. 

Please DM me on Discord - https://discordapp.com/channels/661905455894888490/661905455894888493

Will help through that.

**Comment by o1lab** [comment]
From 1st screenshot, its saying ```expired ``` is an unknown column

From your CLI pls try : ``` DEBUG=knex:* npm run dev```

This will show the problematic query.

**Comment by Tanneguy** [comment]
Good call.
![image](https://user-images.githubusercontent.com/3609703/89715858-1a2bcd00-d9a9-11ea-802e-05259e79c2c5.png)

I do have a `sessions` table in the `scores` database.

**Comment by Tanneguy** [comment]
Congratulations on your reaction time by the way. Since my needs are really basic I was beginning to develop the thing manually and I reported the bug out of good education. However if you are willing to help in such timely manner I will give xc a more serious try.

**Comment by o1lab** [comment]
> I do have a sessions table in the scores database.

Cool, that should be it. 


> Congratulations on your reaction time by the way.

Happy to help. 

> if you are willing to help in such timely manner I will give xc a more serious try.

Yes please give it a try. Happy to help setup over zoom as well. We are overwhelmed by our initial user's responses and their further feedbacks-and-requests on how best we can improve this.

**Comment by Tanneguy** [comment]
Hi, finding the `sessions` does not resolve the issue IMO. Is this forbidden as a table name ?
If yes, then I'd like to have the conventions for using xc.
If not, then how can I avoid the error message ?

**Comment by o1lab** [comment]
Yes, we are internally using sessions

**Comment by o1lab** [comment]
We are internally using sessions table to store express-session.

The name of the table can be changed in server/routers/router.index.js

Please give it a go. I will get this into config from next release.

```
  _getSessionStore() {
    const KnexSessionStore = require("connect-session-knex")(session);

    const store = new KnexSessionStore({
      knex: this.app.$dbs.primaryDb,
      tablename: "sessions"
    });

    return store;
  }
```

**Comment by Tanneguy** [comment]
Ok changing "sessions" to "knex-sessions"  as follows : 

```javascript
  _getSessionStore() {
    const KnexSessionStore = require("connect-session-knex")(session);

    const store = new KnexSessionStore({
      knex: this.app.$dbs.primaryDb,
      tablename: "knex-sessions"
    });

    return store;
  }
```

solves the problem

**Comment by Tanneguy** [comment]
Trying to use the thing once launched produces the error below.
```
(node:20627) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-sessions (sid, expired, sess) values ('XzEfds06u2ET1ASLhuiiAoX_z9ZGKf8d', '2020' at line 1
    at Query.Sequence._packetToError (/sql-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/sql-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/sql-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/sql-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/sql-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/sql-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/sql-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/sql-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:326:12)
    at readableAddChunk (_stream_readable.js:301:11)
    at Socket.Readable.push (_stream_readable.js:235:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
    --------------------
    at Protocol._enqueue (/sql-api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/sql-api/node_modules/mysql/lib/Connection.js:198:25)
    at /sql-api/node_modules/knex/lib/dialects/mysql/index.js:134:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/sql-api/node_modules/knex/lib/dialects/mysql/index.js:128:12)
    at Client_MySQL.query (/sql-api/node_modules/knex/lib/client.js:167:17)
    at Runner.query (/sql-api/node_modules/knex/lib/runner.js:134:36)
    at /sql-api/node_modules/knex/lib/runner.js:40:23
    at /sql-api/node_modules/knex/lib/runner.js:260:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
There must be additional / different steps to really solve the problem.

**Comment by Tanneguy** [comment]
Using a dash within the new name was a hazard.

Problem seems fully solved by replacing "knex-sessions" with "knexsessions"

**Comment by o1lab** [comment]
@Tanneguy ; thank you for the update. This will help others.
