### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by opensorceror** [xgenecloud/xgenecloud#39]
**Feature request is in**
[ ] CLI
[ ] Desktop App
[x] REST API Framework
[ ] GraphQL API Framework

**Is your feature request related to a problem? Please describe.**
I'm currently using the older project - [xmysql](https://github.com/o1lab/xmysql) - and am extremely pleased with the performance. For my MySQL server, it takes ~ 5 ms for INSERT operations. I'm guessing this is because it uses [connection pooling](https://github.com/o1lab/xmysql/blob/2ba88b529332d8593a3f342d15e44a003d9f727c/bin/index.js#L29).

However, with an API generated using xgenecloud, my INSERT operations are taking ~ 25 ms. I'm wondering if this is because it doesn't use connection pooling by default. If so, any pointers on how I can configure this?

**Describe the solution you'd like**
The new API generated using xgenecloud should be as performant or more performant than the one generated using xmysql.

**Describe alternatives you've considered**
For now, I'm continuing to use xmysql until I hear back on this issue.

**Comment by opensorceror** [comment]
Turns out the performance issue was my bad, closing.

For anyone who stumbles onto this issue, [here](http://knexjs.org/#Installation-pooling) is how to configure connection pooling in Knex, if needed. Note that it already has a default pool for MySQL:

> This connection pool has a default setting of a min: 2, max: 10 for the MySQL and PG libraries, and a single connection for sqlite3 (due to issues with utilizing multiple connections on a single file)

**Comment by o1lab** [comment]
hey @opensorceror : thanks for putting this here for others to refer. 

SInce XgeneCloud is completely codebased, it can be easily configured to your needs.

We will try having connection pooling whilst creating the project.
