### ISSUE TITLE
Error return on cmd xc app.install

### ISSUE THREAD

**Issue by rpateld** [xgenecloud/xgenecloud#40]
Following error coming on cmd `xc app.install`
```
Error in xc app.install TypeError: Cannot destructure property `src` of 'undefined' or 'null'.
    at Function.install (C:\installed\node\node_modules\xc-cli\lib\mgr\AppMgr.js:17:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Function.process (C:\installed\node\node_modules\xc-cli\lib\CliMgr.js:211:11)
    at async C:\installed\node\node_modules\xc-cli\index.js:34:5
```

**Comment by o1lab** [comment]
https://xgenecloud.com/download pls download from here for time being.

Did you install xc-cli recently? If not pls update. What OS are you on ?

**Comment by o1lab** [comment]
I see it's windows, ignore that part of question

**Comment by o1lab** [comment]
@rpateld : will be helpful to know which version of windows you using - please as specific as we don't have access to windows machines in team.
