### ISSUE TITLE
(xgenecloud:475): Gtk-WARNING **: 10:33:43.821: cannot open display:

### ISSUE THREAD

**Issue by wenhx8** [xgenecloud/xgenecloud#42]
To exec "xc app.open" cmd has an error  in docker,

**Comment by o1lab** [comment]
Hey, This is not supposed to work in docker :) 

xc app.open opens a desktop application / GUI.

**Comment by o1lab** [comment]
You can generate API code on your ubuntu/windows/mac.

The generated API source code has a dockerfile which can then be run.
