### ISSUE TITLE
Unable to test or save SSL connection

### ISSUE THREAD

**Issue by ap1969** [xgenecloud/xgenecloud#47]
**Bug is in**
[ ] CLI
[x] Desktop App
[ ] REST API Framework 
[ ] GraphQL API Framework

**Describe the bug**
Create a new project with SSL connection (in this case, Digitalocean's managed mysql service) and pressing "Test Database Connection" results in no response. Project cannot be saved.

**To Reproduce**
* Enter normal DB details
* Select "required"
* Point to the certificate (NB: DigitalOcean only supplies a CA cert - I'm not sure if that's normal or not?)
* Press "test database connection"

**Expected behavior**
Either a success or error message should appear, and the project should be saveable.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/1629592/100159002-ed8eb900-2ea4-11eb-928b-5b074b4a116d.PNG)

**Desktop (please complete the following information):**
 - CLI Version 0.3.2
 - Desktop App Version 0.3.18
 - xc-data-mapper version - not sure how to get this. I installed the latest version about a week ago.
 - xc-core version - not sure how to get this.
 - OS: Win 8.1

**Comment by o1lab** [comment]
Please try just REQUIRED-CA option

**Comment by ap1969** [comment]
Hi, I actually gave up with DigitalOcean as I couldn't get it to work. Then tried with ScaleGrid which also has an SSL option, also with just the CA-cert, and that wouldn't work either. But I also couldn't get my desktop HeidiSQL to connect to scalegrid (it did connect to DO OK).

So I've given up with SSL!.

Consider this closed. I'll re-open it or create a new ticket if I swtich back to SSL at any point.

**Comment by o1lab** [comment]
hey @ap1969 , if you give SSL a try. 

Please see if you can do a succesfull connection using [knexjs](http://knexjs.org/) and run a query. We use knexjs for making connections to database and that way we should be able to fix this.

You can always pop in to our [discord](https://discord.gg/5RgZmkW) for any help

**Comment by ap1969** [comment]
Decided I'd spin up a new DB on digitalocean and test this, rather than leave it as a potential issue.

I get the same lack of response when I use either Required-CA or just Required.

**Comment by ap1969** [comment]
A-ha! Got there. It's something weird to do with DO's authentication encryption.

To resolve the issue, I had to create a new user in the DigitalOcean control panel, but select the "Legacy – MySQL 5.x" password encryption method. This is to do with Knex, not your app by the way - the same solution resolves the issue in a basic Knex script, and in the xgenecloud desktop app.

Might be worth putting something in the readme?

Appreciate your help though.

Regards,
Andy

**Comment by o1lab** [comment]
That's cool, could you help & paste solution here.

I will put it up into our docs.

Cheers

**Comment by ap1969** [comment]
Sure:

1. Log into Digitalocean control panel.
2. Click Databases on the left-hand menu
3. Click the database cluster you want to work with.
4. Go to the "Users & Databases" tab
5. Enter the new user's username and select "Legacy – MySQL 5.x" for the Password Encryption.
6. Save the user.

Screenshot of the final screen is attached.

![newuser](https://user-images.githubusercontent.com/1629592/100291461-be944800-2f75-11eb-959b-abc6b3a09156.png)

Hope that helps!

**Comment by o1lab** [comment]
Thank you so much Andy!
