### ISSUE TITLE
Error to connect MSSQL Rest API (CLI)

### ISSUE THREAD

**Issue by LukasCCB** [xgenecloud/xgenecloud#51]
**Bug is in**
[X ] CLI
[ ] Desktop App
[ ] REST API Framework 
[ ] GraphQL API Framework

**Describe the bug**
In CMD Windows:
My connection test OK in Sites/Navicat/External connection. I have tested with db.mywebsite.com and with IP and same problem.

**Screenshots**
https://i.imgur.com/SZEUDWz.png
![image](https://user-images.githubusercontent.com/6683056/103817251-14641180-5045-11eb-8417-cc4663894bf7.png)

**Comment by LukasCCB** [comment]
With localhost is same. The Password is correct, I have tested. What problem.

![image](https://user-images.githubusercontent.com/6683056/103821101-4af15a80-504c-11eb-85e8-9c9ae25e701c.png)

**Comment by o1lab** [comment]
Hey, we are using knex within our libraries.

Could you please check if a simple knex query connection & query works with said mssql database ? 

https://knexjs.org/#Installation-client

**Comment by LukasCCB** [comment]
First, Thanks for help;
Yes, I do a simple project with Knex.

Maybe I should give up.
I don't know what's wrong.
I tried local IP, external IP, local name.
when I go to my PHP and use the same credentials, everything works, only knex won't let me connect.


![image](https://user-images.githubusercontent.com/6683056/103881861-c9d0ac80-50b9-11eb-9a56-c3b383ca8380.png)
![image](https://user-images.githubusercontent.com/6683056/103881875-cccb9d00-50b9-11eb-80c9-2edfadd26dd5.png)
![image](https://user-images.githubusercontent.com/6683056/103881896-d5bc6e80-50b9-11eb-9c7c-b5ac2ec5c6e6.png)

**Comment by o1lab** [comment]
Are you suffixing your server name with port 3541 ? May be that is not required.

See these two : https://github.com/tediousjs/tedious/issues/831, https://github.com/tediousjs/tedious/issues/1079

**Comment by LukasCCB** [comment]
Yes. I have changed 1344 to 3541.
My API ASP.NET, PHP websites, Discord BOT are connecting eith external DB with this port.

 ![image](https://user-images.githubusercontent.com/6683056/103901501-fd223400-50d7-11eb-81ad-84e01d334e39.jpeg)

**Comment by LukasCCB** [comment]
Problem is solved. Thanks o1lab.
For me, I set the options bellow to FALSE.
encrypt> false
enableArithAbort> false

In config_xc.json
"options": {
	"encrypt": false,
	"enableArithAbort": false
}

Just addressing that. You should not have table names with SPACES and SYMBOLS. "- /".
I had to remove these tables and even doing refresh the XC does not detect these changes, I had to delete the project and redo it. Every time I change, add, remove a table or column.

Even so, I am very grateful for the help and attention to the staff.
