### ISSUE TITLE
centos 7/node 10, error in "xc app.open", prompted:/bin/sh: xgenecloud: command not found

### ISSUE THREAD

**Issue by bronzels** [xgenecloud/xgenecloud#59]
**Bug is in**
[ ] CLI
[* ] Desktop App
[ ] REST API Framework 
[ ] GraphQL API Framework

put letter x within relevant [ ] above

**Describe the bug**
install cli and desktop on centos 7 with node rev 10, error in "xc app.open", prompted:/bin/sh: xgenecloud: command not found
if skill "xc app.open" then stuck no response after 1 input:
Your XGENE desktop app is not open - do you want to ? 
  1) Open the app!
  2) Download it for FREE
  Answer: 1

**To Reproduce**
#use this docker file
FROM centos:7.2.1511

RUN cat /etc/redhat-release

WORKDIR /root

ADD node-v10.14.1-linux-x64.tar.gz /root
RUN ln -s node-v10.14.1-linux-x64 node
ENV PATH=$PATH:/root/node/bin

#RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN npm config set registry https://registry.npm.taobao.org
#RUN cnpm install -g xc-cli --unsafe-perm --allow-root
RUN npm install -g xc-cli --unsafe-perm --allow-root
RUN xc --version

#ADD xgenecloud-0.3.18.x86_64.rpm /root
RUN yum -y install gtk3-devel gtk3-devel-docs
RUN yum -y install libXScrnSaver libnotify xdg-utils
RUN mkdir -p /opt/xgenecloud/chrome-sandbox
RUN xc app.install
RUN xc app.open

WORKDIR /

RUN xc gen.apis.rest -u "mssql://192.168.0.85:1433?u=abc&p=abc&d=abc"

**Expected behavior**
no error reported and cli can be used.

**Screenshots**
logs in docker build.
Sending build context to Docker daemon  117.4MB^M^M
Step 1/16 : FROM registry.cn-shanghai.aliyuncs.com/yore/bigdata:7.8.2003_v1
 ---> db0f979c4417
Step 2/16 : RUN cat /etc/redhat-release
 ---> Using cache
 ---> aeeb1fbfbf5a
Step 3/16 : WORKDIR /root
 ---> Using cache
 ---> b9b8c6f2c125
Step 4/16 : ADD node-v10.14.1-linux-x64.tar.gz /root
 ---> Using cache
 ---> fa64237d9ca9
Step 5/16 : RUN ln -s node-v10.14.1-linux-x64 node
 ---> Using cache
 ---> 0deca0d36031
Step 6/16 : ENV PATH=$PATH:/root/node/bin
 ---> Using cache
 ---> 73666fb4b5c0
Step 7/16 : RUN npm config set registry https://registry.npm.taobao.org
 ---> Using cache
 ---> ce929f8ee026
Step 8/16 : RUN npm install -g xc-cli --unsafe-perm --allow-root
 ---> Using cache
 ---> 9b8d67f78c20
Step 9/16 : RUN xc --version
 ---> Using cache
 ---> 670da6a23260
Step 10/16 : ADD xgenecloud-0.3.18.x86_64.rpm /root
 ---> Using cache
 ---> f216973ae032
Step 11/16 : RUN yum -y install gtk3-devel gtk3-devel-docs
 ---> Using cache
 ---> afb079b7205d
Step 12/16 : RUN yum -y install libXScrnSaver libnotify xdg-utils
 ---> Using cache
 ---> 8fcfdb184ebc
Step 13/16 : RUN mkdir -p /opt/xgenecloud/chrome-sandbox
 ---> Using cache
 ---> 85429dcf0a96
Step 14/16 : RUN xc app.install
 ---> Running in 4f5f0c19e8ee
Installable will open automatically now.^[[39m^[[22m^M
^[[1m^[[32mIf not, please install it manually.^[[39m^[[22m^M
^[[?25hRemoving intermediate container 4f5f0c19e8ee
 ---> f4217327b78b
Step 15/16 : RUN xc app.open
 ---> Running in c8855c8df1a8
/bin/sh: xgenecloud: command not found^M
^[[31m^M
^M
Error running command internally^[[39m^M
^[[31m^M
Exiting...^

**Desktop (please complete the following information):**
 - CLI Version [e.g. 0.3.18]
 - Desktop App Version [e.g. 0.3.18]
 - xc-data-mapper version [e.g. 0.3.18]
 - xc-core version [e.g. 0.3.18]
 - OS: [e.g. Linux, centos7]

**Additional context**

**Comment by o1lab** [comment]
I guess, you are trying to run xc gen.apis.* within a docker. This won't work as of now.

Try creating code outside on your machine and then wrap it with docker.
