### ISSUE TITLE
How can I configure https in dev environment.

### ISSUE THREAD

**Issue by sureshbabuinfo** [xgenecloud/xgenecloud#64]
**Feature request is in**
[ ] CLI
[ ] Desktop App
[* ] REST API Framework
[ ] GraphQL API Framework

**Is your feature request related to a problem? Please describe.**
How can I configure https in dev environment.

**Comment by o1lab** [comment]
As mentioned in discord, the project boils down to simple nodejs project - this has to be googled to figure out.
